### ISSUE TITLE
UUID in Enums

### ISSUE THREAD

**Issue by wojciechbator** [kstasik/schema-tools-templates#16]
Right now uuid variant in enum is unsupported, as such definition:

```
          schema:
            oneOf:
              - type: string
                example: 123456
              - description: Globally unique ID
                type: string
                example: 23beb187-f8a3-44b8-9ef8-b31180358dd3
                minLength: 36
                maxLength: 36`

```

Translates to:
```
pub enum AuctionVariant {
  String(string),
  String(string),
}
```
When I change 2nd variant of the above yaml to:

```
          schema:
            oneOf:
              - type: string
                example: 123456
              - description: Globally unique ID
                type: string
                format: uuid
                example: 23beb187-f8a3-44b8-9ef8-b31180358dd3
                minLength: 36
                maxLength: 36`

```
the below error pops out:

```
Error occured: Codegen formatting command error: error: expected one of `(`, `,`, `=`, `{`, or `}`, found `::`
uuid::Uuid(uuid::Uuid),
         ^^ expected one of `(`, `,`, `=`, `{`, or `}`
```

The generated variant causing issue:
```
pub enum AuctionVariant {
  String(string),
  uuid::Uuid(uuid::Uuid),
}
```

I think the solution may be to import uuid::Uuid to file which uses uuid and generate `Uuid(Uuid)` variant in the enum. What do you think?
